//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Matchmaker.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Matchmaker.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///    &quot;repeatMarker&quot;: &quot;&lt;!--repeat--&gt;&quot;,
        ///    &quot;invisible&quot;: &quot;style=\&quot;display:none; \&quot;&quot;,
        ///    &quot;hyperlinkedPlayer&quot;: &quot;&lt;a href=\&quot;javascript:window.external.ClickOnPlayer({0}, {1}, {2})\&quot; style=\&quot;color:#000000; text-decoration: none;\&quot;&gt;{3}&lt;/a&gt;&quot;,
        ///    &quot;typeRinkFunction&quot;: &quot;TypeRink({0}, this.value)&quot;,
        ///    &quot;dropDownTeamSizeStart&quot;: &quot;&lt;select onChange=\&quot;window.external.SelectSize({0}, this.value)\&quot;&gt;&quot;,
        ///    &quot;dropDownTeamSizeOptionNotSelected&quot;: &quot;&lt;option value = \&quot;{0}\&quot; &gt;{1}&lt;/option&gt;&quot;,
        ///    &quot;dropDownTeamSizeOptionSelected&quot; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string elements {
            get {
                return ResourceManager.GetString("elements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;html&gt;
        ///	&lt;head&gt;
        ///		&lt;style&gt;
        ///
        ///			h1 {
        ///				font: 22px Arial, sans-serif;
        ///				font-weight: bold;
        ///				margin-top: 1pt;
        ///				margin-bottom: 1pt;
        ///			}
        ///
        ///			h2 {
        ///				font: 14px Arial, sans-serif;
        ///				text-decoration:underline;
        ///				text-align:left;
        ///				margin-top: 1pt;
        ///				margin-right: 3pt;
        ///				margin-bottom: 3pt;
        ///				margin-left: 3pt;
        ///			}
        ///
        ///			p {
        ///				font: 20px Arial, sans-serif;
        ///				margin-top: 1pt;
        ///				margin-right: 3pt;
        ///				margin-bottom: 1pt;
        ///				margin-left: 3pt;
        ///			}
        ///
        ///			.rink {
        ///		 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string table {
            get {
                return ResourceManager.GetString("table", resourceCulture);
            }
        }
    }
}
